---
title: "HW6"
output:   
  github_document
---

### Load packages and initial setup
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(p8105.datasets)
library(mgcv)
library(modelr)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Question 1

## Question 2

Import data. Create variables `city_state`, `solved` indicator variable. 

```{r}
post <- read_csv("https://raw.github.com/washingtonpost/data-homicides/master/homicide-data.csv") %>%
  janitor::clean_names() %>%
  mutate(city_state = paste(city, state, sep =  ", "),
         solved = ifelse(disposition == "Closed by arrest", 1, 0),
         victim_age = as.numeric(victim_age)) %>%
  filter((city_state != "Tulsa, AL" & city_state != "Dallas, TX" & city_state != "Phoenix, AZ" & city_state != "Kansas City, MO") & (victim_race == "White" | victim_race == "Black")) %>%
  select(city_state, everything())
```

Fit logistic regression model using `glm`. `solved` is the outcome and `victim_age`, `victim_sex`, and `victim_race` are predictors. 

Among homicides in Baltimore, MD

```{r}
fit <-
  post %>%
  filter(city_state == "Baltimore, MD") %>%
  glm(solved ~ victim_age + victim_sex + victim_race, family = binomial (link = "logit"), data = .)

fit %>%
  broom::tidy(conf.int = TRUE) %>%
  mutate(OR = exp(estimate), OR_conf_low = exp(conf.low), OR_conf_high = exp(conf.high)) %>%
  select(term, log_OR = estimate, OR, p.value, OR_conf_low, OR_conf_high) %>%
  knitr::kable(digits = 2)
```

Among all cities

```{r}
all_fit <-
  post %>%
  nest(data = uid:solved) %>%
  mutate(models = map(.x = data, ~glm(solved ~ victim_age + victim_sex + victim_race, family = binomial (link = "logit"), data = .x)),
         results = map(models, broom::tidy)) %>%
  select(city_state, results) %>%
  unnest(results)

```



```{r}
all_fit %>%
  ggplot(aes(x = ))
```


## Question 3

```{r}

```

